language: python
python:
  - "3.6"
before_install:
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov
install:
  - pip install .
script:
  - pytest --cov=./ test/test01.py
after_success:
  - codecov